/*
 * Copyright (c) 2024
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MIK32V2_CLOCKS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MIK32V2_CLOCKS_H_

#define MIK32_CLOCK_CONFIG(reg, bit) \
	(((MIK32_PMGR_ ## reg ## _OFFSET) << 6U) | (bit))

/**
 * @name Register offsets
 * @{
 */

#define MIK32_PMGR_DIV_AHB_OFFSET 0x00
#define MIK32_PMGR_DIV_APBM_OFFSET 0x04
#define MIK32_PMGR_DIV_APBP_OFFSET 0x08

#define MIK32_PMGR_AHB_SET_OFFSET        0x0CU
#define MIK32_PMGR_APBM_SET_OFFSET       0x14U
#define MIK32_PMGR_APBP_SET_OFFSET       0x1CU

#define MIK32_PMGR_TIMER_CFG_OFFSET       0x30U

/** @} */

/**
 * @name Clock enable/disable definitions for peripherals
 * @{
 */

/* AHB peripherals */
#define MIK32_CLOCK_CORE	MIK32_CLOCK_CONFIG(AHB_SET, 0U)
#define MIK32_CLOCK_EEPROM      MIK32_CLOCK_CONFIG(AHB_SET, 1U)
#define MIK32_CLOCK_RAM		MIK32_CLOCK_CONFIG(AHB_SET, 2U)
#define MIK32_CLOCK_SPIFI	MIK32_CLOCK_CONFIG(AHB_SET, 3U)
#define MIK32_CLOCK_TCB		MIK32_CLOCK_CONFIG(AHB_SET, 4U)
#define MIK32_CLOCK_DMA		MIK32_CLOCK_CONFIG(AHB_SET, 5U)
#define MIK32_CLOCK_CRYPT	MIK32_CLOCK_CONFIG(AHB_SET, 6U)
#define MIK32_CLOCK_CRC32	MIK32_CLOCK_CONFIG(AHB_SET, 7U)

/* APBM peripherals */
#define MIK32_CLOCK_POWERMON    MIK32_CLOCK_CONFIG(APBM_SET, 0U)
#define MIK32_CLOCK_EPIC	MIK32_CLOCK_CONFIG(APBM_SET, 1U)
#define MIK32_CLOCK_TIMER32_0   MIK32_CLOCK_CONFIG(APBM_SET, 2U)
#define MIK32_CLOCK_OUTPUT	MIK32_CLOCK_CONFIG(APBM_SET, 3U)
#define MIK32_CLOCK_BUSWDT	MIK32_CLOCK_CONFIG(APBM_SET, 4U)
#define MIK32_CLOCK_OTP		MIK32_CLOCK_CONFIG(APBM_SET, 5U)
#define MIK32_CLOCK_SYSPOWERMON MIK32_CLOCK_CONFIG(APBM_SET, 6U)
#define MIK32_CLOCK_BATWU       MIK32_CLOCK_CONFIG(APBM_SET, 7U)
#define MIK32_CLOCK_RTC		MIK32_CLOCK_CONFIG(APBM_SET, 8U)

/* APBP peripherals */
#define MIK32_CLOCK_WDT		MIK32_CLOCK_CONFIG(APBP_SET, 0U)
#define MIK32_CLOCK_USART0      MIK32_CLOCK_CONFIG(APBP_SET, 1U)
#define MIK32_CLOCK_USART1      MIK32_CLOCK_CONFIG(APBP_SET, 2U)
#define MIK32_CLOCK_TIMER16_0   MIK32_CLOCK_CONFIG(APBP_SET, 3U)
#define MIK32_CLOCK_TIMER16_1   MIK32_CLOCK_CONFIG(APBP_SET, 4U)
#define MIK32_CLOCK_TIMER16_2   MIK32_CLOCK_CONFIG(APBP_SET, 5U)
#define MIK32_CLOCK_TIMER32_1   MIK32_CLOCK_CONFIG(APBP_SET, 6U)
#define MIK32_CLOCK_TIMER32_2   MIK32_CLOCK_CONFIG(APBP_SET, 7U)
#define MIK32_CLOCK_SPI0	MIK32_CLOCK_CONFIG(APBP_SET, 8U)
#define MIK32_CLOCK_SPI1	MIK32_CLOCK_CONFIG(APBP_SET, 9U)
#define MIK32_CLOCK_I2C0	MIK32_CLOCK_CONFIG(APBP_SET, 10U)
#define MIK32_CLOCK_I2C1	MIK32_CLOCK_CONFIG(APBP_SET, 11U)
#define MIK32_CLOCK_GPIO0	MIK32_CLOCK_CONFIG(APBP_SET, 12U)
#define MIK32_CLOCK_GPIO1	MIK32_CLOCK_CONFIG(APBP_SET, 13U)
#define MIK32_CLOCK_GPIO2	MIK32_CLOCK_CONFIG(APBP_SET, 14U)
#define MIK32_CLOCK_ANALOG	MIK32_CLOCK_CONFIG(APBP_SET, 15U)
#define MIK32_CLOCK_GPIO_IRQ	MIK32_CLOCK_CONFIG(APBP_SET, 16U)

/** @} */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MIK32V2_CLOCKS_H_ */
